### PR TITLE
Update to 21.01

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
Added some patches. Introduces some warnings though.

**Comment by leozide** [comment]
Have you tried https://github.com/leozide/leocad/commit/1b0a47f692fa788166b065f3105085660436f5ef? That may be a better fix, I'm guessing aarch uses GLES.

**Comment by hfiguiere** [comment]
I has GL 3.2. But Qt is a bit weird.

**Comment by leozide** [comment]
It's probably Qt then, the docs say we shouldn't need to include GL.h directly. We probably don't need the defines at the top that are causing conflicts but I don't have an easy way to test.

**Comment by hfiguiere** [comment]
I can look at that too.

BTW I haven't run this build yet on aarch64. :-/

**Pull request merged**
